window.QITP_DATABASE = {
  "total_items": 141,
  "items": [
    {
      "id": 1,
      "row": 19,
      "category": "GENERAL REQUIREMENTS",
      "trade": "LGU PERMITS AND COMPLIANCE",
      "item_no": "1.",
      "description": "Identify Required Permits, ECC, Dole report",
      "characteristics": "Scope of work, location, type of construction, applicable laws",
      "procedure": "Checklist Review",
      "acceptance_criteria": "All required permits identified (e.g., building, zoning, fire)",
      "frequency": "Once per project",
      "records": "Building permit forms, ECC, Dole Report",
      "control_forms": "",
      "qa_reference": "Local Building Code, Project Scope",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 2,
      "row": 20,
      "category": "GENERAL REQUIREMENTS",
      "trade": "LGU PERMITS AND COMPLIANCE",
      "item_no": "2.",
      "description": "Prepare Permit Applications",
      "characteristics": "Completeness of forms, accuracy of drawings, supporting documents, signatures",
      "procedure": "Document Verification",
      "acceptance_criteria": "All documents complete and accurate",
      "frequency": "Per application",
      "records": "Building permit forms, ECC, Dole Report",
      "control_forms": "",
      "qa_reference": "Permit Guidelines, Application Forms",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 3,
      "row": 21,
      "category": "GENERAL REQUIREMENTS",
      "trade": "LGU PERMITS AND COMPLIANCE",
      "item_no": "3.",
      "description": "Submit to Authorities",
      "characteristics": "Submission date, authority name, tracking number, receipt confirmation",
      "procedure": "Submission Confirmation",
      "acceptance_criteria": "Submission acknowledged by authority",
      "frequency": "Per submission",
      "records": "Building permit forms, ECC, Dole Report",
      "control_forms": "",
      "qa_reference": "Submission Logs, Email Confirmations",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 4,
      "row": 22,
      "category": "GENERAL REQUIREMENTS",
      "trade": "LGU PERMITS AND COMPLIANCE",
      "item_no": "4.",
      "description": "Track Permit Status",
      "characteristics": "Permit number, current status (pending/approved), follow-up actions",
      "procedure": "Status Monitoring",
      "acceptance_criteria": "Status updated and documented weekly",
      "frequency": "Weekly",
      "records": "Building permit forms, ECC, Dole Report",
      "control_forms": "",
      "qa_reference": "Permit Tracker, Communication Records",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 5,
      "row": 23,
      "category": "GENERAL REQUIREMENTS",
      "trade": "LGU PERMITS AND COMPLIANCE",
      "item_no": "5.",
      "description": "Respond to Authority Queries",
      "characteristics": "Nature of query, response timeline, revised documents, communication logs",
      "procedure": "Document Review",
      "acceptance_criteria": "Timely and accurate responses submitted",
      "frequency": "As needed",
      "records": "Building permit forms, ECC, Dole Report",
      "control_forms": "",
      "qa_reference": "Authority Correspondence, Revised Documents",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 6,
      "row": 24,
      "category": "GENERAL REQUIREMENTS",
      "trade": "LGU PERMITS AND COMPLIANCE",
      "item_no": "6.",
      "description": "Receive Approved Permits",
      "characteristics": "Permit number, scope match, conditions, expiration date",
      "procedure": "Document Check",
      "acceptance_criteria": "Permit matches scope and includes all required approvals",
      "frequency": "Per permit",
      "records": "Building permit forms, ECC, Dole Report",
      "control_forms": "",
      "qa_reference": "Approved Permit Documents",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 7,
      "row": 25,
      "category": "GENERAL REQUIREMENTS",
      "trade": "LGU PERMITS AND COMPLIANCE",
      "item_no": "7.",
      "description": "Distribute Permits to Site Team",
      "characteristics": "Recipient name, date of distribution, acknowledgment signature",
      "procedure": "Distribution Log",
      "acceptance_criteria": "Site team receives and acknowledges permit documents",
      "frequency": "Once per permit",
      "records": "Building permit forms, ECC, Dole Report",
      "control_forms": "",
      "qa_reference": "Distribution Records",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 8,
      "row": 26,
      "category": "GENERAL REQUIREMENTS",
      "trade": "LGU PERMITS AND COMPLIANCE",
      "item_no": "8.",
      "description": "Display Permits on Site",
      "characteristics": "Visibility, weatherproofing, location (e.g., entrance, site office)",
      "procedure": "Visual Inspection",
      "acceptance_criteria": "Permits posted in visible location as required",
      "frequency": "Once per site setup",
      "records": "Building permit forms, ECC, Dole Report",
      "control_forms": "",
      "qa_reference": "Site Setup Checklist",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 9,
      "row": 27,
      "category": "GENERAL REQUIREMENTS",
      "trade": "LGU PERMITS AND COMPLIANCE",
      "item_no": "9.",
      "description": "Maintain Permit Records",
      "characteristics": "Filing system, backup method, accessibility, version control",
      "procedure": "Document Audit",
      "acceptance_criteria": "All permits filed, accessible, and backed up",
      "frequency": "Monthly",
      "records": "Building permit forms, ECC, Dole Report",
      "control_forms": "",
      "qa_reference": "Permit Archive, Digital Backup",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 10,
      "row": 31,
      "category": "STRUCTURAL WORKS",
      "trade": "REBAR WORKS",
      "item_no": "1.",
      "description": "Material Delivery Inspection",
      "characteristics": "Bar diameter, length, grade, rust, bends, mill certificate",
      "procedure": "Visual & Certification Check",
      "acceptance_criteria": "Conforms to approved specs; free from rust, oil, and damage",
      "frequency": "Per delivery batch",
      "records": "Delivery docs",
      "control_forms": "",
      "qa_reference": "Material Spec, Mill Certificate",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 11,
      "row": 32,
      "category": "STRUCTURAL WORKS",
      "trade": "REBAR WORKS",
      "item_no": "2.",
      "description": "Storage of Rebars",
      "characteristics": "Off-ground stacking, covered storage, separation by size/grade",
      "procedure": "Visual Inspection",
      "acceptance_criteria": "Stored to prevent corrosion and contamination",
      "frequency": "Weekly",
      "records": "Rebar works checklist forms",
      "control_forms": "",
      "qa_reference": "Storage Guidelines, Site QA Manual",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 12,
      "row": 33,
      "category": "STRUCTURAL WORKS",
      "trade": "REBAR WORKS",
      "item_no": "3.",
      "description": "Cutting and Bending",
      "characteristics": "Bar length, bend radius, cutting tolerance",
      "procedure": "Dimensional Check",
      "acceptance_criteria": "As per bar bending schedule (BBS); no cracks or splits",
      "frequency": "Per batch",
      "records": "Rebar works checklist forms",
      "control_forms": "",
      "qa_reference": "BBS, Structural Drawings",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 13,
      "row": 34,
      "category": "STRUCTURAL WORKS",
      "trade": "REBAR WORKS",
      "item_no": "4.",
      "description": "Surface Preparation",
      "characteristics": "Cleanliness, rust, oil, paint, scale",
      "procedure": "Visual Inspection",
      "acceptance_criteria": "Surface clean and free of contaminants",
      "frequency": "Before installation",
      "records": "Rebar works checklist forms",
      "control_forms": "",
      "qa_reference": "Rebar Handling Procedure",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 14,
      "row": 35,
      "category": "STRUCTURAL WORKS",
      "trade": "REBAR WORKS",
      "item_no": "5.",
      "description": "Placement and Fixing",
      "characteristics": "Bar spacing, cover, alignment, lap length, supports",
      "procedure": "Visual & Dimensional Check",
      "acceptance_criteria": "As per drawings; cover blocks in place; ties secure",
      "frequency": "Per structural element",
      "records": "Rebar works checklist forms",
      "control_forms": "",
      "qa_reference": "Structural Drawings, Rebar Spec",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 15,
      "row": 36,
      "category": "STRUCTURAL WORKS",
      "trade": "REBAR WORKS",
      "item_no": "6.",
      "description": "Reinforcement for Openings",
      "characteristics": "Additional bars, trimming, anchorage",
      "procedure": "Visual Inspection",
      "acceptance_criteria": "Reinforcement provided as per approved details",
      "frequency": "Per opening",
      "records": "Rebar works checklist forms",
      "control_forms": "",
      "qa_reference": "Opening Details, Structural Drawings",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 16,
      "row": 37,
      "category": "STRUCTURAL WORKS",
      "trade": "REBAR WORKS",
      "item_no": "7.",
      "description": "Welding (if applicable)",
      "characteristics": "Weld type, length, penetration, defects",
      "procedure": "Visual & NDT (if required)",
      "acceptance_criteria": "Welds meet AWS or local code; no cracks or undercuts",
      "frequency": "Per weld",
      "records": "Rebar works checklist forms",
      "control_forms": "",
      "qa_reference": "Welding Spec, AWS D1.4",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 17,
      "row": 38,
      "category": "STRUCTURAL WORKS",
      "trade": "REBAR WORKS",
      "item_no": "8.",
      "description": "Rebar Couplers (if used)",
      "characteristics": "Thread engagement, alignment, torque",
      "procedure": "Torque Test, Visual Check",
      "acceptance_criteria": "Couplers installed per manufacturer\u2019s spec; torque within limits",
      "frequency": "Per connection",
      "records": "Rebar works checklist forms",
      "control_forms": "",
      "qa_reference": "Coupler Spec, Manufacturer Guidelines",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 18,
      "row": 39,
      "category": "STRUCTURAL WORKS",
      "trade": "REBAR WORKS",
      "item_no": "9.",
      "description": "Final Inspection Before Pour",
      "characteristics": "All bars in place, supports secure, no displacement",
      "procedure": "Visual & Checklist Review",
      "acceptance_criteria": "Approved by QA/QC and Engineer before concrete pour",
      "frequency": "Before concreting",
      "records": "Rebar works checklist forms",
      "control_forms": "",
      "qa_reference": "Pre-Pour Checklist, Inspection Report",
      "subcon": "H",
      "gencon": "H",
      "consultant": "H"
    },
    {
      "id": 19,
      "row": 42,
      "category": "STRUCTURAL WORKS",
      "trade": "FORM WORKS",
      "item_no": "1.",
      "description": "Material Delivery Inspection",
      "characteristics": "Plywood type, timber/steel sections, release agents, form ties",
      "procedure": "Visual & Certification Check",
      "acceptance_criteria": "Materials conform to specs; no damage or warping",
      "frequency": "Per delivery batch",
      "records": "",
      "control_forms": "",
      "qa_reference": "Material Spec, Delivery Documents",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 20,
      "row": 43,
      "category": "STRUCTURAL WORKS",
      "trade": "FORM WORKS",
      "item_no": "2.",
      "description": "Storage of Formwork Materials",
      "characteristics": "Off-ground stacking, covered storage, separation by type",
      "procedure": "Visual Inspection",
      "acceptance_criteria": "Stored to prevent moisture damage and deformation",
      "frequency": "Weekly",
      "records": "",
      "control_forms": "",
      "qa_reference": "Storage Guidelines, Site QA Manual",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 21,
      "row": 44,
      "category": "STRUCTURAL WORKS",
      "trade": "FORM WORKS",
      "item_no": "3.",
      "description": "Formwork Assembly",
      "characteristics": "Alignment, dimensions, joint tightness, support spacing",
      "procedure": "Visual & Dimensional Check",
      "acceptance_criteria": "As per drawings; joints sealed; supports secure",
      "frequency": "Per structural element",
      "records": "",
      "control_forms": "",
      "qa_reference": "Structural Drawings, Formwork Spec",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 22,
      "row": 45,
      "category": "STRUCTURAL WORKS",
      "trade": "FORM WORKS",
      "item_no": "4.",
      "description": "Formwork Support & Bracing",
      "characteristics": "Props spacing, bracing tightness, load capacity",
      "procedure": "Visual & Load Check",
      "acceptance_criteria": "Stable and secure; spacing per design; no movement under load",
      "frequency": "Per setup",
      "records": "",
      "control_forms": "",
      "qa_reference": "Method Statement, Safety Guidelines",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 23,
      "row": 46,
      "category": "STRUCTURAL WORKS",
      "trade": "FORM WORKS",
      "item_no": "5.",
      "description": "Opening and Embedment Setup",
      "characteristics": "Location, size, anchorage, sealing",
      "procedure": "Visual Inspection",
      "acceptance_criteria": "Matches drawing; securely fixed; no gaps",
      "frequency": "Per opening",
      "records": "",
      "control_forms": "",
      "qa_reference": "Architectural Drawings, Fixture Details",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 24,
      "row": 47,
      "category": "STRUCTURAL WORKS",
      "trade": "FORM WORKS",
      "item_no": "6.",
      "description": "Application of Release Agent",
      "characteristics": "Coverage, compatibility, cleanliness",
      "procedure": "Visual Inspection",
      "acceptance_criteria": "Uniform application; no pooling or contamination",
      "frequency": "Before concrete pour",
      "records": "",
      "control_forms": "",
      "qa_reference": "Manufacturer Instructions, Method Statement",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 25,
      "row": 48,
      "category": "STRUCTURAL WORKS",
      "trade": "FORM WORKS",
      "item_no": "7.",
      "description": "Final Pre-Pour Inspection",
      "characteristics": "Cleanliness, alignment, dimensions, embedded items",
      "procedure": "Visual & Checklist Review",
      "acceptance_criteria": "Approved by QA/QC and Engineer before concrete pour",
      "frequency": "Before concreting",
      "records": "Pre-Pour Checklist, Inspection Report",
      "control_forms": "",
      "qa_reference": "",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 26,
      "row": 49,
      "category": "STRUCTURAL WORKS",
      "trade": "FORM WORKS",
      "item_no": "8.",
      "description": "Formwork Removal",
      "characteristics": "Concrete strength, curing time, surface finish",
      "procedure": "Visual & Timing Check",
      "acceptance_criteria": "Removal only after required strength achieved; no damage to concrete",
      "frequency": "Per element",
      "records": "",
      "control_forms": "",
      "qa_reference": "Removal Guidelines, Concrete Spec",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 27,
      "row": 50,
      "category": "STRUCTURAL WORKS",
      "trade": "FORM WORKS",
      "item_no": "9.",
      "description": "Post-Removal Surface Check",
      "characteristics": "Honeycombing, alignment, surface defects",
      "procedure": "Visual Inspection",
      "acceptance_criteria": "Surface acceptable; no major defects; ready for next stage",
      "frequency": "Per element",
      "records": "Inspection Report",
      "control_forms": "",
      "qa_reference": "QAQC manual",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 28,
      "row": 53,
      "category": "STRUCTURAL WORKS",
      "trade": "CONCRETE WORKS",
      "item_no": "1.",
      "description": "Material Delivery Inspection",
      "characteristics": "Cement type, aggregates, admixtures, water source, batch tickets",
      "procedure": "Visual & Certification Check",
      "acceptance_criteria": "Materials conform to specs; no contamination or damage",
      "frequency": "Per delivery batch",
      "records": "",
      "control_forms": "",
      "qa_reference": "Material Spec, Delivery Documents",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 29,
      "row": 54,
      "category": "STRUCTURAL WORKS",
      "trade": "CONCRETE WORKS",
      "item_no": "2.",
      "description": "Concrete Mix Verification",
      "characteristics": "Cement ratio, slump, strength, admixture dosage",
      "procedure": "Mix Design Review",
      "acceptance_criteria": "Mix design approved; meets structural and durability requirements",
      "frequency": "Per mix design",
      "records": "",
      "control_forms": "",
      "qa_reference": "Mix Design Report, Project Specs",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 30,
      "row": 55,
      "category": "STRUCTURAL WORKS",
      "trade": "CONCRETE WORKS",
      "item_no": "3.",
      "description": "Batching and Mixing",
      "characteristics": "Mixing time, uniformity, water-cement ratio",
      "procedure": "Visual & Time Check",
      "acceptance_criteria": "Uniform mix; no segregation; correct water-cement ratio",
      "frequency": "Per batch",
      "records": "",
      "control_forms": "",
      "qa_reference": "Batching Procedure, Method Statement",
      "subcon": "H",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 31,
      "row": 56,
      "category": "STRUCTURAL WORKS",
      "trade": "CONCRETE WORKS",
      "item_no": "4.",
      "description": "Slump Test",
      "characteristics": "Slump height, cone shape, collapse",
      "procedure": "Field Test",
      "acceptance_criteria": "Slump within specified range (e.g., 75\u2013125 mm for normal workability)",
      "frequency": "Per batch",
      "records": "",
      "control_forms": "",
      "qa_reference": "ASTM C143, Project Specs",
      "subcon": "H",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 32,
      "row": 57,
      "category": "STRUCTURAL WORKS",
      "trade": "CONCRETE WORKS",
      "item_no": "5.",
      "description": "Concrete Placement",
      "characteristics": "Pouring method, temperature, segregation, vibration",
      "procedure": "Visual & Temperature Check",
      "acceptance_criteria": "No cold joints; temperature within limits; proper compaction",
      "frequency": "Per pour",
      "records": "",
      "control_forms": "",
      "qa_reference": "Pouring Procedure, Method Statement",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 33,
      "row": 58,
      "category": "STRUCTURAL WORKS",
      "trade": "CONCRETE WORKS",
      "item_no": "6.",
      "description": "Cube/Cylinder Sampling",
      "characteristics": "Sample size, curing method, labeling",
      "procedure": "Field Sampling",
      "acceptance_criteria": "Samples taken per spec; cured properly; labeled clearly",
      "frequency": "Per batch",
      "records": "",
      "control_forms": "",
      "qa_reference": "ASTM C31, Sampling Procedure",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 34,
      "row": 59,
      "category": "STRUCTURAL WORKS",
      "trade": "CONCRETE WORKS",
      "item_no": "7.",
      "description": "Compressive Strength Test",
      "characteristics": "Load application, failure mode, strength value",
      "procedure": "Lab Test",
      "acceptance_criteria": "Strength meets or exceeds design requirement",
      "frequency": "14-days & 28-days",
      "records": "",
      "control_forms": "",
      "qa_reference": "ASTM C39, Test Report",
      "subcon": "H",
      "gencon": "H",
      "consultant": "H"
    },
    {
      "id": 35,
      "row": 60,
      "category": "STRUCTURAL WORKS",
      "trade": "CONCRETE WORKS",
      "item_no": "8.",
      "description": "Surface Finish Inspection",
      "characteristics": "Honeycombing, cracks, alignment, texture",
      "procedure": "Visual Inspection",
      "acceptance_criteria": "Surface smooth; no major defects; matches architectural intent",
      "frequency": "After setting",
      "records": "",
      "control_forms": "",
      "qa_reference": "Finishing Spec, Inspection Checklist",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 36,
      "row": 61,
      "category": "STRUCTURAL WORKS",
      "trade": "CONCRETE WORKS",
      "item_no": "9.",
      "description": "Curing Process",
      "characteristics": "Moisture retention, coverage, curing duration",
      "procedure": "Visual & Time Check",
      "acceptance_criteria": "Curing maintained as per spec (e.g., 7 days for normal concrete)",
      "frequency": "Daily (min 7 days)",
      "records": "",
      "control_forms": "",
      "qa_reference": "Curing Guidelines, Method Statement",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 37,
      "row": 62,
      "category": "STRUCTURAL WORKS",
      "trade": "CONCRETE WORKS",
      "item_no": "10.",
      "description": "Final Inspection and Handover",
      "characteristics": "As-built drawings, test reports, surface condition",
      "procedure": "Visual & Document Review",
      "acceptance_criteria": "All documentation complete; concrete meets design and finish criteria",
      "frequency": "Once per element",
      "records": "",
      "control_forms": "",
      "qa_reference": "As-built Drawings, Handover Checklist",
      "subcon": "H",
      "gencon": "H",
      "consultant": "H"
    },
    {
      "id": 38,
      "row": 67,
      "category": "ARCHITECTURAL WORKS",
      "trade": "CHB LAYING",
      "item_no": "1.",
      "description": "Material Delivery (CHB)",
      "characteristics": "Size, strength, appearance",
      "procedure": "Visual / document review",
      "acceptance_criteria": "No cracks; uniform size; min. 500 psi",
      "frequency": "Per delivery",
      "records": "Test results",
      "control_forms": "",
      "qa_reference": "CHB Specs / Supplier Cert",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 39,
      "row": 68,
      "category": "ARCHITECTURAL WORKS",
      "trade": "CHB LAYING",
      "item_no": "2.",
      "description": "Mortar Mixing",
      "characteristics": "Ratio, consistency, workability",
      "procedure": "Visual / slump test",
      "acceptance_criteria": "1:3 cement:sand; workable mix",
      "frequency": "Per batch",
      "records": "Masonry works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Method Statement",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 40,
      "row": 69,
      "category": "ARCHITECTURAL WORKS",
      "trade": "CHB LAYING",
      "item_no": "3.",
      "description": "Layout and Alignment",
      "characteristics": "Wall line, plumb, level",
      "procedure": "Measurement / visual",
      "acceptance_criteria": "\u00b13mm tolerance; vert and hor alignment",
      "frequency": "Per wall section",
      "records": "Masonry works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Approved Plans",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 41,
      "row": 70,
      "category": "ARCHITECTURAL WORKS",
      "trade": "CHB LAYING",
      "item_no": "4.",
      "description": "CHB Installation",
      "characteristics": "Bonding, joint thickness, alignment",
      "procedure": "10mm joint; staggered bond; plumb wall",
      "acceptance_criteria": "Continuous",
      "frequency": "Per wall section",
      "records": "Masonry works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Method Statement",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 42,
      "row": 71,
      "category": "ARCHITECTURAL WORKS",
      "trade": "CHB LAYING",
      "item_no": "5.",
      "description": "Reinforcement (Vert & Hor)",
      "characteristics": "Bar size, spacing, embedment",
      "procedure": "As per structural plans; proper embedment",
      "acceptance_criteria": "Per wall section",
      "frequency": "Per wall section",
      "records": "Masonry works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Structural Plans",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 43,
      "row": 72,
      "category": "ARCHITECTURAL WORKS",
      "trade": "CHB LAYING",
      "item_no": "6.",
      "description": "Grouting of Cells",
      "characteristics": "Grout mix, completeness",
      "procedure": "Full grout fill in reinforced cells",
      "acceptance_criteria": "Per lift",
      "frequency": "Per wall section",
      "records": "Masonry works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Method Statement",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 44,
      "row": 73,
      "category": "ARCHITECTURAL WORKS",
      "trade": "CHB LAYING",
      "item_no": "7.",
      "description": "Curing of CHB Wall",
      "characteristics": "Moisture retention, duration",
      "procedure": "Minimum 7 days moist curing",
      "acceptance_criteria": "Daily",
      "frequency": "Per wall section",
      "records": "Masonry works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Manufacturer\u2019s Guide",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 45,
      "row": 74,
      "category": "ARCHITECTURAL WORKS",
      "trade": "CHB LAYING",
      "item_no": "8.",
      "description": "Final Inspection",
      "characteristics": "Cracks, alignment, surface finish",
      "procedure": "No cracks; plumb and level; sound wall",
      "acceptance_criteria": "1",
      "frequency": "Per wall section",
      "records": "Masonry works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Project Specs",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 46,
      "row": 75,
      "category": "ARCHITECTURAL WORKS",
      "trade": "CHB LAYING",
      "item_no": "9.",
      "description": "Handover Documentation",
      "characteristics": "Completeness, accuracy",
      "procedure": "Signed ITP, test results, approvals",
      "acceptance_criteria": "Complete and signed ITP, test results, and approvals",
      "frequency": "Once after turnover",
      "records": "Masonry works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "QAQC Manual",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 47,
      "row": 78,
      "category": "ARCHITECTURAL WORKS",
      "trade": "PLASTERING WORKS",
      "item_no": "1.",
      "description": "Material Delivery (Cement, Sand, Additives)",
      "characteristics": "Type, grade, shelf life",
      "procedure": "Document review / visual",
      "acceptance_criteria": "Materials conform to specs; no expired stock",
      "frequency": "Per delivery",
      "records": "Delivery Receipt",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Material Specs",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 48,
      "row": 79,
      "category": "ARCHITECTURAL WORKS",
      "trade": "PLASTERING WORKS",
      "item_no": "2.",
      "description": "Surface Preparation",
      "characteristics": "Cleanliness, dryness, bonding surface",
      "procedure": "Visual inspection",
      "acceptance_criteria": "Surface clean, roughened or primed as required",
      "frequency": "1",
      "records": "Masonry works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "QAQC Manual",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 49,
      "row": 80,
      "category": "ARCHITECTURAL WORKS",
      "trade": "PLASTERING WORKS",
      "item_no": "3.",
      "description": "Mixing of Plaster",
      "characteristics": "Ratio, consistency, workability",
      "procedure": "Visual / slump test",
      "acceptance_criteria": "1:3 or as specified; workable mix",
      "frequency": "Per batch",
      "records": "Masonry works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Method Statement",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 50,
      "row": 81,
      "category": "ARCHITECTURAL WORKS",
      "trade": "PLASTERING WORKS",
      "item_no": "4.",
      "description": "Application of Plaster",
      "characteristics": "Thickness, bonding, uniformity",
      "procedure": "Straight edge / caliper",
      "acceptance_criteria": "10\u201315mm per coat; no hollow areas",
      "frequency": "Continuous",
      "records": "Masonry works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Project Specs",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 51,
      "row": 82,
      "category": "ARCHITECTURAL WORKS",
      "trade": "PLASTERING WORKS",
      "item_no": "5.",
      "description": "Curing of Plaster",
      "characteristics": "Moisture retention, duration",
      "procedure": "Minimum 3\u20137 days moist curing",
      "acceptance_criteria": "Daily",
      "frequency": "Per wall section",
      "records": "Masonry works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Manufacturer\u2019s Guide",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 52,
      "row": 83,
      "category": "ARCHITECTURAL WORKS",
      "trade": "PLASTERING WORKS",
      "item_no": "6.",
      "description": "Final Inspection",
      "characteristics": "Cracks, finish, levelness, adhesion",
      "procedure": "No cracks; smooth finish; sound adhesion",
      "acceptance_criteria": "1",
      "frequency": "Per wall section",
      "records": "Masonry works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Project Specs",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 53,
      "row": 84,
      "category": "ARCHITECTURAL WORKS",
      "trade": "PLASTERING WORKS",
      "item_no": "7.",
      "description": "Handover Documentation",
      "characteristics": "Completeness, accuracy",
      "procedure": "Signed ITP, test results, approvals",
      "acceptance_criteria": "Complete and signed ITP, test results, and approvals",
      "frequency": "Once after turnover",
      "records": "Masonry works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "QAQC Manual",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 54,
      "row": 87,
      "category": "ARCHITECTURAL WORKS",
      "trade": "FLOOR TOPPING",
      "item_no": "1.",
      "description": "Surface Preparation",
      "characteristics": "Clean, dry, free from dust, laitance, and loose particles",
      "procedure": "Visual inspection",
      "acceptance_criteria": "No contaminants; surface roughness within spec",
      "frequency": "1",
      "records": "Topping works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201010",
      "qa_reference": "Project Specs / Manufacturer\u2019s Guide",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 55,
      "row": 88,
      "category": "ARCHITECTURAL WORKS",
      "trade": "FLOOR TOPPING",
      "item_no": "2.",
      "description": "Formwork & Edge Restraints",
      "characteristics": "Proper alignment, secured, and sealed",
      "procedure": "Visual and dimensional check",
      "acceptance_criteria": "No gaps; dimensions within tolerance",
      "frequency": "1",
      "records": "Topping works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201010",
      "qa_reference": "Approved Shop Drawings",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 56,
      "row": 89,
      "category": "ARCHITECTURAL WORKS",
      "trade": "FLOOR TOPPING",
      "item_no": "3.",
      "description": "Rebar / Wire Mesh Installation",
      "characteristics": "Correct spacing, size, and placement",
      "procedure": "Visual and measurement",
      "acceptance_criteria": "As per structural drawings",
      "frequency": "1",
      "records": "Topping works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201010",
      "qa_reference": "Reinforcement Details",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 57,
      "row": 90,
      "category": "ARCHITECTURAL WORKS",
      "trade": "FLOOR TOPPING",
      "item_no": "4.",
      "description": "Mixing of Floor Topping",
      "characteristics": "Correct ratio and consistency",
      "procedure": "Batch record / slump test",
      "acceptance_criteria": "Mix ratio per approved design; slump 75\u2013100mm (if applicable)",
      "frequency": "Every batch",
      "records": "Topping works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201010",
      "qa_reference": "Method Statement",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 58,
      "row": 91,
      "category": "ARCHITECTURAL WORKS",
      "trade": "FLOOR TOPPING",
      "item_no": "5.",
      "description": "Pouring of Floor Topping",
      "characteristics": "Uniform placement, no segregation",
      "procedure": "Visual and level check",
      "acceptance_criteria": "Even surface; no honeycombing",
      "frequency": "Continuous monitoring",
      "records": "Topping works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201010",
      "qa_reference": "Method Statement",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 59,
      "row": 92,
      "category": "ARCHITECTURAL WORKS",
      "trade": "FLOOR TOPPING",
      "item_no": "6.",
      "description": "Screeding / Leveling",
      "characteristics": "Surface level and finish",
      "procedure": "Straight edge / laser level",
      "acceptance_criteria": "\u00b13mm tolerance over 3m length",
      "frequency": "1",
      "records": "Topping works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201010",
      "qa_reference": "Project Specifications",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 60,
      "row": 93,
      "category": "ARCHITECTURAL WORKS",
      "trade": "FLOOR TOPPING",
      "item_no": "7.",
      "description": "Curing",
      "characteristics": "Moist curing or curing compound application",
      "procedure": "Visual / curing log",
      "acceptance_criteria": "Minimum 7 days moist curing or as specified",
      "frequency": "Daily during curing",
      "records": "Topping works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201010",
      "qa_reference": "Manufacturer\u2019s Guide / Specs",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 61,
      "row": 94,
      "category": "ARCHITECTURAL WORKS",
      "trade": "FLOOR TOPPING",
      "item_no": "8.",
      "description": "Final Inspection",
      "characteristics": "Surface finish, cracks, levelness",
      "procedure": "Visual / hammer tap / level test",
      "acceptance_criteria": "No cracks; level within tolerance; sound surface",
      "frequency": "1",
      "records": "Topping works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201010",
      "qa_reference": "Project Specifications",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 62,
      "row": 95,
      "category": "ARCHITECTURAL WORKS",
      "trade": "FLOOR TOPPING",
      "item_no": "9.",
      "description": "Handover Documentation",
      "characteristics": "Submission of inspection records and approvals",
      "procedure": "Document review",
      "acceptance_criteria": "Complete and signed ITP, test results, and approvals",
      "frequency": "Once per area",
      "records": "Topping works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201010",
      "qa_reference": "QAQC Manual",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 63,
      "row": 98,
      "category": "ARCHITECTURAL WORKS",
      "trade": "TILES WORKS",
      "item_no": "1.",
      "description": "Surface preparation",
      "characteristics": "Surface dryness and cleanliness, Levelness and slope, Curing status of substrate",
      "procedure": "Visual & dimensional check",
      "acceptance_criteria": "\u00b13 mm level tolerance, No dust, oil, laitance",
      "frequency": "Once per area before tiling",
      "records": "Tile works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201015",
      "qa_reference": "Method Statement for Tiling",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 64,
      "row": 99,
      "category": "ARCHITECTURAL WORKS",
      "trade": "TILES WORKS",
      "item_no": "2.",
      "description": "Tile, adhesive, grout inspection",
      "characteristics": "Tile type, size, batch number, Expiry date of adhesive/grout, Manufacturer\u2019s compliance",
      "procedure": "Verification & documentation",
      "acceptance_criteria": "As per approved submittals, No damage or mismatch",
      "frequency": "Per delivery batch",
      "records": "Tile works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201015",
      "qa_reference": "Project Specifications",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 65,
      "row": 100,
      "category": "ARCHITECTURAL WORKS",
      "trade": "TILES WORKS",
      "item_no": "3.",
      "description": "Tile layout and alignment",
      "characteristics": "Grid accuracy , Expansion/control joints , Symmetry and aesthetics",
      "procedure": "Visual check & measurement",
      "acceptance_criteria": "As per shop drawings , Joints aligned and spaced",
      "frequency": "Once per room/zone",
      "records": "Tile works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201015",
      "qa_reference": "Approved Shop Drawings",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 66,
      "row": 101,
      "category": "ARCHITECTURAL WORKS",
      "trade": "TILES WORKS",
      "item_no": "4.",
      "description": "Adhesive application, tile laying",
      "characteristics": "Adhesive coverage (\u226590%) , Tile bond strength , Joint width uniformity , Lippage control",
      "procedure": "Random sampling & supervision",
      "acceptance_criteria": "No hollow tiles , Max lippage: 1 mm for walls, 2 mm for floors",
      "frequency": "Daily or per 20 m\u00b2",
      "records": "Tile works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201015",
      "qa_reference": "Method Statement for Tiling",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 67,
      "row": 102,
      "category": "ARCHITECTURAL WORKS",
      "trade": "TILES WORKS",
      "item_no": "5.",
      "description": "Grout mixing and application",
      "characteristics": "Grout consistency , Joint fill completeness , Color uniformity , No cracks or pinholes",
      "procedure": "Visual & adhesion test",
      "acceptance_criteria": "Smooth, even joints , No shrinkage or discoloration",
      "frequency": "Per area after curing",
      "records": "Tile works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201015",
      "qa_reference": "Method Statement for Tiling",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 68,
      "row": 103,
      "category": "ARCHITECTURAL WORKS",
      "trade": "TILES WORKS",
      "item_no": "6.",
      "description": "Cleanliness, alignment, finish",
      "characteristics": "Surface finish and sheen , No stains or adhesive residue , Edge trims and skirting , Drainage slope (wet areas)",
      "procedure": "Punch list & checklist",
      "acceptance_criteria": "No visible defects , Falls to floor waste: 1\u20132% slope",
      "frequency": "Once per completed room/zone",
      "records": "Tile works checklist",
      "control_forms": "FM\u2010OPN\u201002\u201015",
      "qa_reference": "CAPA-weekly inspection report",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 69,
      "row": 107,
      "category": "PLUMBING SANITARY WORKS",
      "trade": "SANITARY SYSTEM",
      "item_no": "1.",
      "description": "Material Delivery Inspection",
      "characteristics": "Type of fixtures, accessories, manufacturer certificate, damage-free condition",
      "procedure": "Visual & Certification Check",
      "acceptance_criteria": "Materials conform to specs; no visible damage",
      "frequency": "Per delivery batch",
      "records": "Delivery Documents",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Material Spec",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 70,
      "row": 108,
      "category": "PLUMBING SANITARY WORKS",
      "trade": "SANITARY SYSTEM",
      "item_no": "2.",
      "description": "Layout Marking",
      "characteristics": "Fixture locations, pipe routes, spacing, accessibility",
      "procedure": "Visual & Dimensional Check",
      "acceptance_criteria": "Markings match approved drawings and ergonomic standards",
      "frequency": "Per room/area",
      "records": "flow test checklist form",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Sanitary Layout Drawings",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 71,
      "row": 109,
      "category": "PLUMBING SANITARY WORKS",
      "trade": "SANITARY SYSTEM",
      "item_no": "3.",
      "description": "Pipe Installation (Drainage)",
      "characteristics": "Pipe slope, alignment, support spacing, joint sealing",
      "procedure": "Visual & Slope Measurement",
      "acceptance_criteria": "Slope within design tolerance; joints sealed and aligned",
      "frequency": "Per installed section",
      "records": "flow test checklist form",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Drainage Spec, Local Code",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 72,
      "row": 110,
      "category": "PLUMBING SANITARY WORKS",
      "trade": "SANITARY SYSTEM",
      "item_no": "4.",
      "description": "Fixture Installation",
      "characteristics": "Mounting height, alignment, water flow, drainage, sealing",
      "procedure": "Visual & Functional Check",
      "acceptance_criteria": "Fixtures securely mounted; functional and leak-free",
      "frequency": "Per fixture",
      "records": "flow test checklist form",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Manufacturer Instructions",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 73,
      "row": 111,
      "category": "PLUMBING SANITARY WORKS",
      "trade": "SANITARY SYSTEM",
      "item_no": "5.",
      "description": "Water Supply Connection",
      "characteristics": "Test pressure, duration, leakage observation",
      "procedure": "Pressure Test",
      "acceptance_criteria": "No leaks; pressure maintained for required duration",
      "frequency": "Per system segment",
      "records": "flow test checklist form",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Pressure Test Procedure, Local Code",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 74,
      "row": 112,
      "category": "PLUMBING SANITARY WORKS",
      "trade": "SANITARY SYSTEM",
      "item_no": "6.",
      "description": "Drainage Leak Test",
      "characteristics": "Flow test, air pressure, visual inspection",
      "procedure": "Water or Air Test",
      "acceptance_criteria": "No leaks; flow unobstructed; air pressure holds",
      "frequency": "Per system segment",
      "records": "flow test checklist form",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Drainage Test Procedure, Local Code",
      "subcon": "H",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 75,
      "row": 113,
      "category": "PLUMBING SANITARY WORKS",
      "trade": "SANITARY SYSTEM",
      "item_no": "7.",
      "description": "Sealant and Caulking Inspection",
      "characteristics": "Coverage, adhesion, cleanliness",
      "procedure": "Visual Inspection",
      "acceptance_criteria": "Sealant applied neatly and fully around fixture edges",
      "frequency": "Per fixture",
      "records": "flow test checklist form",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Manufacturer Instructions, Finishing Spec",
      "subcon": "H",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 76,
      "row": 114,
      "category": "PLUMBING SANITARY WORKS",
      "trade": "SANITARY SYSTEM",
      "item_no": "8.",
      "description": "Final Inspection and Handover",
      "characteristics": "As-built drawings, test reports, fixture operation",
      "procedure": "Visual & Document Review",
      "acceptance_criteria": "System matches design; all fixtures operational",
      "frequency": "Once per system",
      "records": "flow test checklist form",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "As-built Drawings, Handover Checklist",
      "subcon": "H",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 77,
      "row": 117,
      "category": "PLUMBING SANITARY WORKS",
      "trade": "PLUMBING SYSTEM",
      "item_no": "1.",
      "description": "Material Delivery Inspection",
      "characteristics": "Pipe type, fittings, valves, insulation, manufacturer certificate",
      "procedure": "Visual & Certification Check",
      "acceptance_criteria": "Materials conform to specs; no damage or defects",
      "frequency": "Per delivery batch",
      "records": "Delivery Documents",
      "control_forms": "",
      "qa_reference": "Material Spec",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 78,
      "row": 118,
      "category": "PLUMBING SANITARY WORKS",
      "trade": "PLUMBING SYSTEM",
      "item_no": "2.",
      "description": "Rough-In Installation",
      "characteristics": "Pipe routing, slope, support spacing, fixture locations",
      "procedure": "Visual & Dimensional Check",
      "acceptance_criteria": "Pipes installed per drawings; slope within tolerance; securely supported",
      "frequency": "Before concealment",
      "records": "Leak test checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Plumbing Layout, Local Code",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 79,
      "row": 119,
      "category": "PLUMBING SANITARY WORKS",
      "trade": "PLUMBING SYSTEM",
      "item_no": "3.",
      "description": "Fixture Installation",
      "characteristics": "Alignment, secure mounting, water flow, drainage",
      "procedure": "Visual & Functional Check",
      "acceptance_criteria": "Fixtures properly aligned and functional",
      "frequency": "Per fixture",
      "records": "Leak test checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Fixture Spec, Manufacturer Instructions",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 80,
      "row": 120,
      "category": "PLUMBING SANITARY WORKS",
      "trade": "PLUMBING SYSTEM",
      "item_no": "4.",
      "description": "Pressure Testing (Water Supply)",
      "characteristics": "Test pressure, duration, leakage observation",
      "procedure": "Hydrostatic Test",
      "acceptance_criteria": "No leaks; pressure maintained for required duration",
      "frequency": "Per system segment",
      "records": "Leak test checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Pressure Test Procedure, Local Code",
      "subcon": "H",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 81,
      "row": 121,
      "category": "PLUMBING SANITARY WORKS",
      "trade": "PLUMBING SYSTEM",
      "item_no": "5.",
      "description": "Insulation of Pipes",
      "characteristics": "Coverage, material type, adhesion, thickness",
      "procedure": "Visual Inspection",
      "acceptance_criteria": "Insulation complete and conforms to spec",
      "frequency": "After installation",
      "records": "Leak test checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "Insulation Spec, Energy Code",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 82,
      "row": 122,
      "category": "PLUMBING SANITARY WORKS",
      "trade": "PLUMBING SYSTEM",
      "item_no": "6.",
      "description": "Final System Inspection",
      "characteristics": "As-built drawings, test reports, fixture operation",
      "procedure": "Visual & Document Review",
      "acceptance_criteria": "System matches design; all fixtures operational",
      "frequency": "Once per system",
      "records": "Leak test checklist",
      "control_forms": "FM\u2010OPN\u201002\u201014",
      "qa_reference": "As-built Drawings, Handover Checklist",
      "subcon": "H",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 83,
      "row": 126,
      "category": "MECHANICAL WORKS",
      "trade": "FIRE PROTECTION WORKS",
      "item_no": "1.",
      "description": "Material Delivery Inspection",
      "characteristics": "Pipe type, sprinkler heads, valves, gauges, manufacturer certificates",
      "procedure": "Visual & Certification Check",
      "acceptance_criteria": "Materials conform to specs; no damage or corrosion",
      "frequency": "Per delivery batch",
      "records": "Delivery docs",
      "control_forms": "",
      "qa_reference": "Material Spec, Delivery Documents",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 84,
      "row": 127,
      "category": "MECHANICAL WORKS",
      "trade": "FIRE PROTECTION WORKS",
      "item_no": "2.",
      "description": "Layout Marking",
      "characteristics": "Pipe routing, sprinkler spacing, coverage area",
      "procedure": "Visual & Dimensional Check",
      "acceptance_criteria": "Matches approved fire protection drawings",
      "frequency": "Per zone",
      "records": "Fire protection checklist form",
      "control_forms": "",
      "qa_reference": "Fire Protection Layout, NFPA Standards",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 85,
      "row": 128,
      "category": "MECHANICAL WORKS",
      "trade": "FIRE PROTECTION WORKS",
      "item_no": "3.",
      "description": "Pipe Installation",
      "characteristics": "Pipe alignment, support spacing, joint sealing",
      "procedure": "Visual & Alignment Check",
      "acceptance_criteria": "Pipes securely fixed; joints sealed; slope per design",
      "frequency": "Per installed section",
      "records": "Fire protection checklist form",
      "control_forms": "",
      "qa_reference": "Installation Method Statement",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 86,
      "row": 129,
      "category": "MECHANICAL WORKS",
      "trade": "FIRE PROTECTION WORKS",
      "item_no": "4.",
      "description": "Sprinkler Head Installation",
      "characteristics": "Type, orientation, spacing, coverage",
      "procedure": "Visual & Position Check",
      "acceptance_criteria": "Heads installed per spec; unobstructed spray pattern",
      "frequency": "Per head",
      "records": "Fire protection checklist form",
      "control_forms": "",
      "qa_reference": "NFPA 13, Manufacturer Instructions",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 87,
      "row": 130,
      "category": "MECHANICAL WORKS",
      "trade": "FIRE PROTECTION WORKS",
      "item_no": "5.",
      "description": "Valve and Control Device Setup",
      "characteristics": "Valve type, accessibility, signage, operation",
      "procedure": "Functional & Visual Check",
      "acceptance_criteria": "Devices installed per spec; operational and labeled",
      "frequency": "Per device",
      "records": "Fire protection checklist form",
      "control_forms": "",
      "qa_reference": "Valve Schedule, Fire Safety Code",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 88,
      "row": 131,
      "category": "MECHANICAL WORKS",
      "trade": "FIRE PROTECTION WORKS",
      "item_no": "6.",
      "description": "Hydrostatic Pressure Testing",
      "characteristics": "Test pressure, duration, leakage observation",
      "procedure": "Pressure Test",
      "acceptance_criteria": "No leaks; pressure maintained for required duration",
      "frequency": "Per system segment",
      "records": "leak test form",
      "control_forms": "",
      "qa_reference": "NFPA 13, Pressure Test Procedure",
      "subcon": "H",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 89,
      "row": 132,
      "category": "MECHANICAL WORKS",
      "trade": "FIRE PROTECTION WORKS",
      "item_no": "7.",
      "description": "Alarm System Integration",
      "characteristics": "Signal transmission, device response, control panel alerts",
      "procedure": "Functional Test",
      "acceptance_criteria": "All devices respond correctly; signals reach control panel",
      "frequency": "Per zone",
      "records": "Fire protection checklist form",
      "control_forms": "",
      "qa_reference": "NFPA 72, System Integration Plan",
      "subcon": "X",
      "gencon": "W",
      "consultant": "S"
    },
    {
      "id": 90,
      "row": 133,
      "category": "MECHANICAL WORKS",
      "trade": "FIRE PROTECTION WORKS",
      "item_no": "8.",
      "description": "Final System Commissioning",
      "characteristics": "End-to-end operation, alarms, water flow, documentation",
      "procedure": "Full System Test",
      "acceptance_criteria": "System fully operational; all tests passed; documents complete",
      "frequency": "Once per system",
      "records": "Commisioning report",
      "control_forms": "",
      "qa_reference": "Commissioning Checklist, As-built Drawings",
      "subcon": "H",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 91,
      "row": 136,
      "category": "MECHANICAL WORKS",
      "trade": "ELEVATOR INSTALLATION",
      "item_no": "1.",
      "description": "Material Delivery Inspection",
      "characteristics": "Elevator components (rails, cabin, motor, controller), manufacturer certificates",
      "procedure": "Visual & Certification Check",
      "acceptance_criteria": "Materials conform to specs; no damage; valid certifications",
      "frequency": "Per delivery batch",
      "records": "",
      "control_forms": "",
      "qa_reference": "Material Spec, Delivery Documents",
      "subcon": "X",
      "gencon": "H",
      "consultant": "S"
    },
    {
      "id": 92,
      "row": 137,
      "category": "MECHANICAL WORKS",
      "trade": "ELEVATOR INSTALLATION",
      "item_no": "2.",
      "description": "Shaft & Pit Preparation",
      "characteristics": "Shaft dimensions, plumb, pit depth, waterproofing, embedded items",
      "procedure": "Dimensional & Visual Check",
      "acceptance_criteria": "Matches approved shop drawings; clean and dry pit",
      "frequency": "Once per shaft",
      "records": "Elevator inspection checklist form",
      "control_forms": "",
      "qa_reference": "Civil Drawings, Manufacturer Requirements",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 93,
      "row": 138,
      "category": "MECHANICAL WORKS",
      "trade": "ELEVATOR INSTALLATION",
      "item_no": "3.",
      "description": "Rail & Bracket Installation",
      "characteristics": "Vertical alignment, bracket spacing, torque of fasteners",
      "procedure": "Alignment & Torque Check",
      "acceptance_criteria": "Rails plumb within tolerance; brackets secured",
      "frequency": "Per floor",
      "records": "Elevator inspection checklist form",
      "control_forms": "",
      "qa_reference": "Manufacturer Manual, Installation Plan",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 94,
      "row": 139,
      "category": "MECHANICAL WORKS",
      "trade": "ELEVATOR INSTALLATION",
      "item_no": "4.",
      "description": "Machine Room Setup",
      "characteristics": "Machine base, vibration pads, power supply, ventilation, lighting",
      "procedure": "Visual & Functional Check",
      "acceptance_criteria": "Equipment installed per spec; room meets code",
      "frequency": "Once per machine room",
      "records": "Elevator inspection checklist form",
      "control_forms": "",
      "qa_reference": "Electrical Layout, Elevator Spec",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 95,
      "row": 140,
      "category": "MECHANICAL WORKS",
      "trade": "ELEVATOR INSTALLATION",
      "item_no": "5.",
      "description": "Elevator Car & Counterweight Install",
      "characteristics": "Car frame, sling, guide shoes, buffers, counterweight alignment",
      "procedure": "Visual & Dimensional Check",
      "acceptance_criteria": "Installed per drawings; clearances within tolerance",
      "frequency": "Per unit",
      "records": "Elevator inspection checklist form",
      "control_forms": "",
      "qa_reference": "Manufacturer Manual, Shop Drawings",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 96,
      "row": 141,
      "category": "MECHANICAL WORKS",
      "trade": "ELEVATOR INSTALLATION",
      "item_no": "6.",
      "description": "Wiring & Control Panel Setup",
      "characteristics": "Cable routing, termination, labeling, control panel configuration",
      "procedure": "Continuity & Function Test",
      "acceptance_criteria": "Properly terminated; labeled; control logic matches design",
      "frequency": "Per system",
      "records": "Elevator inspection checklist form",
      "control_forms": "",
      "qa_reference": "Wiring Diagram, Labeling Plan",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 97,
      "row": 142,
      "category": "MECHANICAL WORKS",
      "trade": "ELEVATOR INSTALLATION",
      "item_no": "7.",
      "description": "Safety Gear & Limit Switches",
      "characteristics": "Governor, overspeed switch, buffers, final limit switches",
      "procedure": "Functional Test",
      "acceptance_criteria": "All safety devices functional and tested",
      "frequency": "Per unit",
      "records": "Elevator inspection checklist form",
      "control_forms": "",
      "qa_reference": "Safety Code, Manufacturer Instructions",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 98,
      "row": 143,
      "category": "MECHANICAL WORKS",
      "trade": "ELEVATOR INSTALLATION",
      "item_no": "8.",
      "description": "Door Mechanism Installation",
      "characteristics": "Door alignment, interlocks, sensors, smooth operation",
      "procedure": "Visual & Functional Check",
      "acceptance_criteria": "Doors operate smoothly; interlocks functional",
      "frequency": "Per door",
      "records": "Elevator inspection checklist form",
      "control_forms": "",
      "qa_reference": "Door Schedule, Manufacturer Manual",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 99,
      "row": 144,
      "category": "MECHANICAL WORKS",
      "trade": "ELEVATOR INSTALLATION",
      "item_no": "9.",
      "description": "Load Test & Speed Test",
      "characteristics": "Rated load, travel speed, leveling accuracy",
      "procedure": "Performance Test",
      "acceptance_criteria": "Meets rated capacity and speed; levels within tolerance",
      "frequency": "Once per unit",
      "records": "Elevator inspection checklist form",
      "control_forms": "",
      "qa_reference": "EN 81, ASME A17.1, Test Report",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 100,
      "row": 145,
      "category": "MECHANICAL WORKS",
      "trade": "ELEVATOR INSTALLATION",
      "item_no": "10.",
      "description": "Emergency Operation Test",
      "characteristics": "Battery backup, manual lowering, alarm, intercom",
      "procedure": "Functional Test",
      "acceptance_criteria": "Emergency systems functional; response time within limits",
      "frequency": "Once per unit",
      "records": "Elevator inspection checklist form",
      "control_forms": "",
      "qa_reference": "Emergency Plan, Safety Code",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 101,
      "row": 146,
      "category": "MECHANICAL WORKS",
      "trade": "ELEVATOR INSTALLATION",
      "item_no": "11.",
      "description": "Final Inspection & Commissioning",
      "characteristics": "As-built drawings, test certificates, operation manuals",
      "procedure": "Visual & Document Review",
      "acceptance_criteria": "All documentation complete; system approved by authority",
      "frequency": "Once per unit",
      "records": "Commisioning report",
      "control_forms": "",
      "qa_reference": "Handover Checklist, Commissioning Docs",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 102,
      "row": 150,
      "category": "ELECTRONICS WORKS",
      "trade": "FDAS INSTALLATION",
      "item_no": "1.",
      "description": "Material Delivery Inspection",
      "characteristics": "Smoke detectors, heat detectors, control panels, wiring, manufacturer certificates",
      "procedure": "Visual & Certification Check",
      "acceptance_criteria": "Materials conform to specs; no damage; valid certifications",
      "frequency": "Per delivery batch",
      "records": "Delivery Documents",
      "control_forms": "",
      "qa_reference": "Material Spec, NFPA 72",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 103,
      "row": 151,
      "category": "ELECTRONICS WORKS",
      "trade": "FDAS INSTALLATION",
      "item_no": "2.",
      "description": "Layout Marking",
      "characteristics": "Detector locations, panel placement, cable routes",
      "procedure": "Visual & Dimensional Check",
      "acceptance_criteria": "Matches approved FDAS layout drawings",
      "frequency": "Per zone",
      "records": "FDAS checklist form",
      "control_forms": "",
      "qa_reference": "FDAS Layout, Fire Safety Code",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 104,
      "row": 152,
      "category": "ELECTRONICS WORKS",
      "trade": "FDAS INSTALLATION",
      "item_no": "3.",
      "description": "Device Installation",
      "characteristics": "Mounting height, orientation, accessibility, wiring",
      "procedure": "Visual & Functional Check",
      "acceptance_criteria": "Devices securely mounted; wiring per spec; no obstructions",
      "frequency": "Per device",
      "records": "FDAS checklist form",
      "control_forms": "",
      "qa_reference": "Manufacturer Instructions, NFPA 72",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 105,
      "row": 153,
      "category": "ELECTRONICS WORKS",
      "trade": "FDAS INSTALLATION",
      "item_no": "4.",
      "description": "Cable Routing and Termination",
      "characteristics": "Cable type, insulation, labeling, termination quality",
      "procedure": "Visual & Continuity Test",
      "acceptance_criteria": "Cables properly routed and terminated; continuity confirmed, labeling at both ends",
      "frequency": "Per circuit",
      "records": "FDAS checklist form",
      "control_forms": "",
      "qa_reference": "Wiring Diagram, PEC/NFPA Standards",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 106,
      "row": 154,
      "category": "ELECTRONICS WORKS",
      "trade": "FDAS INSTALLATION",
      "item_no": "5.",
      "description": "Control Panel Setup",
      "characteristics": "Panel configuration, power supply, battery backup",
      "procedure": "Visual & Power-On Test",
      "acceptance_criteria": "Panel operational; configured per design; backup functional",
      "frequency": "Per panel",
      "records": "FDAS checklist form",
      "control_forms": "",
      "qa_reference": "Panel Spec, NFPA 72",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 107,
      "row": 155,
      "category": "ELECTRONICS WORKS",
      "trade": "FDAS INSTALLATION",
      "item_no": "6.",
      "description": "System Integration",
      "characteristics": "Signal transmission, device response, alarm activation",
      "procedure": "Functional Test",
      "acceptance_criteria": "All devices respond correctly; alarms trigger as designed",
      "frequency": "Per zone",
      "records": "FDAS checklist form",
      "control_forms": "",
      "qa_reference": "Integration Plan, NFPA 72",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 108,
      "row": 156,
      "category": "ELECTRONICS WORKS",
      "trade": "FDAS INSTALLATION",
      "item_no": "7.",
      "description": "End-to-End System Testing",
      "characteristics": "Detector activation, alarm response, panel logging",
      "procedure": "Full System Test",
      "acceptance_criteria": "System fully operational; no faults; logs recorded",
      "frequency": "Once per system",
      "records": "FDAS checklist form",
      "control_forms": "",
      "qa_reference": "Commissioning Checklist, Test Reports",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 109,
      "row": 157,
      "category": "ELECTRONICS WORKS",
      "trade": "FDAS INSTALLATION",
      "item_no": "8.",
      "description": "Final Inspection and Handover",
      "characteristics": "As-built drawings, test certificates, user training",
      "procedure": "Visual & Document Review",
      "acceptance_criteria": "All documentation complete; system approved by authority",
      "frequency": "Once per project",
      "records": "Commisioning report",
      "control_forms": "",
      "qa_reference": "As-built Drawings, Handover Checklist",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 110,
      "row": 160,
      "category": "ELECTRONICS WORKS",
      "trade": "STRUCTURED CABELING",
      "item_no": "1.",
      "description": "Material Delivery Inspection",
      "characteristics": "Cable type (UTP/STP/fiber), connectors, patch panels, labeling materials",
      "procedure": "Visual & Certification Check",
      "acceptance_criteria": "Materials conform to specs; no damage; valid certifications",
      "frequency": "Per delivery batch",
      "records": "Delivery Docs",
      "control_forms": "",
      "qa_reference": "Material Spec, ANSI/TIA-568",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 111,
      "row": 161,
      "category": "ELECTRONICS WORKS",
      "trade": "STRUCTURED CABELING",
      "item_no": "2.",
      "description": "Layout Marking",
      "characteristics": "Cable routes, outlet locations, rack positions",
      "procedure": "Visual & Dimensional Check",
      "acceptance_criteria": "Matches approved cabling layout drawings",
      "frequency": "Per floor/zone",
      "records": "",
      "control_forms": "",
      "qa_reference": "Cabling Layout, Network Plan",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 112,
      "row": 162,
      "category": "ELECTRONICS WORKS",
      "trade": "STRUCTURED CABELING",
      "item_no": "3.",
      "description": "Conduit and Raceway Installation",
      "characteristics": "Conduit type, alignment, support spacing, bend radius",
      "procedure": "Visual & Alignment Check",
      "acceptance_criteria": "Installed per layout; securely fixed; joints sealed",
      "frequency": "Per section",
      "records": "",
      "control_forms": "",
      "qa_reference": "Method Statement, NEC/PEC Standards",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 113,
      "row": 163,
      "category": "ELECTRONICS WORKS",
      "trade": "STRUCTURED CABELING",
      "item_no": "4.",
      "description": "Cable Pulling and Termination",
      "characteristics": "Cable type, bend radius, termination quality, labeling at both ends",
      "procedure": "Visual & Continuity Test",
      "acceptance_criteria": "Cables properly routed and terminated; labels match drawings",
      "frequency": "Per cable run",
      "records": "",
      "control_forms": "",
      "qa_reference": "ANSI/TIA-568, Manufacturer Instructions",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 114,
      "row": 164,
      "category": "ELECTRONICS WORKS",
      "trade": "STRUCTURED CABELING",
      "item_no": "5.",
      "description": "Patch Panel and Rack Setup",
      "characteristics": "Mounting, cable management, labeling of ports and cables",
      "procedure": "Visual & Functional Check",
      "acceptance_criteria": "Patch panels securely mounted; cables organized and labeled",
      "frequency": "Per rack",
      "records": "",
      "control_forms": "",
      "qa_reference": "Rack Layout, Cabling Schedule",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 115,
      "row": 165,
      "category": "ELECTRONICS WORKS",
      "trade": "STRUCTURED CABELING",
      "item_no": "6.",
      "description": "Labeling and Documentation",
      "characteristics": "Label format (font, size), location, cable ID, rack ID, outlet ID",
      "procedure": "Visual & Document Review",
      "acceptance_criteria": "Labels are legible, durable, standardized, and match documentation",
      "frequency": "Per zone/system",
      "records": "",
      "control_forms": "",
      "qa_reference": "Labeling Plan, As-built Drawings",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 116,
      "row": 166,
      "category": "ELECTRONICS WORKS",
      "trade": "STRUCTURED CABELING",
      "item_no": "7.",
      "description": "Testing of Copper Cabling",
      "characteristics": "Wire map, length, attenuation, NEXT, return loss",
      "procedure": "Fluke/Continuity Test",
      "acceptance_criteria": "Passes Category 5e/6/6A performance criteria",
      "frequency": "Per cable run",
      "records": "",
      "control_forms": "",
      "qa_reference": "ANSI/TIA-1152, Test Report",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 117,
      "row": 167,
      "category": "ELECTRONICS WORKS",
      "trade": "STRUCTURED CABELING",
      "item_no": "8.",
      "description": "Testing of Fiber Cabling",
      "characteristics": "Insertion loss, reflectance, continuity",
      "procedure": "OTDR/OLTS Test",
      "acceptance_criteria": "Passes single-mode/multi-mode specs; no breaks or high loss",
      "frequency": "Per fiber run",
      "records": "",
      "control_forms": "",
      "qa_reference": "ANSI/TIA-568.3-D, Test Report",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 118,
      "row": 168,
      "category": "ELECTRONICS WORKS",
      "trade": "STRUCTURED CABELING",
      "item_no": "9.",
      "description": "Final Inspection and Handover",
      "characteristics": "As-built drawings, test certificates, labeling verification",
      "procedure": "Visual & Functional Review",
      "acceptance_criteria": "All documentation complete; system approved by client/consultant",
      "frequency": "Once per system",
      "records": "",
      "control_forms": "",
      "qa_reference": "Handover Checklist, Commissioning Docs",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 119,
      "row": 171,
      "category": "ELECTRONICS WORKS",
      "trade": "CCTV INSTALLATION",
      "item_no": "1.",
      "description": "Material Delivery Inspection",
      "characteristics": "Camera type (IP/analog), NVR/DVR, cables, connectors, brackets, manufacturer certificates",
      "procedure": "Visual & Certification Check",
      "acceptance_criteria": "Materials conform to specs; no damage; valid certifications",
      "frequency": "Per delivery batch",
      "records": "",
      "control_forms": "",
      "qa_reference": "Material Spec, Delivery Documents",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 120,
      "row": 172,
      "category": "ELECTRONICS WORKS",
      "trade": "CCTV INSTALLATION",
      "item_no": "2.",
      "description": "Layout Marking",
      "characteristics": "Camera locations, cable routes, power source, field of view",
      "procedure": "Visual & Dimensional Check",
      "acceptance_criteria": "Matches approved CCTV layout drawings",
      "frequency": "Per zone",
      "records": "",
      "control_forms": "",
      "qa_reference": "CCTV Layout, Security Plan",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 121,
      "row": 173,
      "category": "ELECTRONICS WORKS",
      "trade": "CCTV INSTALLATION",
      "item_no": "3.",
      "description": "Cable Tray Installation",
      "characteristics": "Tray type, support spacing, bonding, labeling",
      "procedure": "Visual & Alignment Check",
      "acceptance_criteria": "Trays securely mounted; aligned; bonded; labeled per zone",
      "frequency": "Per tray section",
      "records": "",
      "control_forms": "",
      "qa_reference": "Cable Tray Layout, NEC/NEMA Standards",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 122,
      "row": 174,
      "category": "ELECTRONICS WORKS",
      "trade": "CCTV INSTALLATION",
      "item_no": "4.",
      "description": "Cable Pulling and Termination",
      "characteristics": "Cable type (coaxial/UTP), bend radius, termination quality, labeling",
      "procedure": "Visual & Continuity Test",
      "acceptance_criteria": "Cables properly routed and terminated; labeled at both ends",
      "frequency": "Per cable run",
      "records": "",
      "control_forms": "",
      "qa_reference": "Manufacturer Instructions, Labeling Plan",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 123,
      "row": 175,
      "category": "ELECTRONICS WORKS",
      "trade": "CCTV INSTALLATION",
      "item_no": "5.",
      "description": "Camera Mounting and Alignment",
      "characteristics": "Mounting height, orientation, coverage area, accessibility",
      "procedure": "Visual & Functional Check",
      "acceptance_criteria": "Cameras securely mounted; field of view unobstructed",
      "frequency": "Per camera",
      "records": "",
      "control_forms": "",
      "qa_reference": "Camera Spec, Installation Manual",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 124,
      "row": 176,
      "category": "ELECTRONICS WORKS",
      "trade": "CCTV INSTALLATION",
      "item_no": "6.",
      "description": "Labeling of Devices and Cables",
      "characteristics": "Label format, location, legibility, durability",
      "procedure": "Visual & Document Review",
      "acceptance_criteria": "Labels match drawings; standardized format; heat/smudge resistant",
      "frequency": "Per zone/system",
      "records": "",
      "control_forms": "",
      "qa_reference": "Labeling Plan, As-built Drawings",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 125,
      "row": 177,
      "category": "ELECTRONICS WORKS",
      "trade": "CCTV INSTALLATION",
      "item_no": "7.",
      "description": "Power Supply Verification",
      "characteristics": "Voltage level, current draw, backup availability",
      "procedure": "Voltage & Load Test",
      "acceptance_criteria": "Power within spec; backup systems operational",
      "frequency": "Per camera/system",
      "records": "",
      "control_forms": "",
      "qa_reference": "Power Plan, Electrical Layout",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 126,
      "row": 178,
      "category": "ELECTRONICS WORKS",
      "trade": "CCTV INSTALLATION",
      "item_no": "8.",
      "description": "Network Configuration (IP CCTV)",
      "characteristics": "IP address, connectivity, bandwidth, recording settings",
      "procedure": "Software & Connectivity Test",
      "acceptance_criteria": "Cameras reachable; recording functional; network stable",
      "frequency": "Per camera/system",
      "records": "",
      "control_forms": "",
      "qa_reference": "Network Plan, IP Allocation Sheet",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 127,
      "row": 179,
      "category": "ELECTRONICS WORKS",
      "trade": "CCTV INSTALLATION",
      "item_no": "9.",
      "description": "System Integration (BMS/FDAS)",
      "characteristics": "Signal transmission, alarm triggers, control panel response",
      "procedure": "End-to-End Test",
      "acceptance_criteria": "Integrated systems respond correctly; events logged",
      "frequency": "Once per integrated system",
      "records": "",
      "control_forms": "",
      "qa_reference": "Integration Plan, NFPA/IEC Standards",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 128,
      "row": 180,
      "category": "ELECTRONICS WORKS",
      "trade": "CCTV INSTALLATION",
      "item_no": "10.",
      "description": "Final Testing and Commissioning",
      "characteristics": "Live feed, recording, playback, remote access, PTZ control",
      "procedure": "Functional Test",
      "acceptance_criteria": "All functions operational; no faults; client approval",
      "frequency": "Once per system",
      "records": "",
      "control_forms": "",
      "qa_reference": "Commissioning Checklist, Test Reports",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 129,
      "row": 184,
      "category": "ELECTRICAL SYSTEM",
      "trade": "ELECTRICAL WORKS",
      "item_no": "1.",
      "description": "Design Review",
      "characteristics": "Load calculations, circuit layout, panel schedules, grounding plan",
      "procedure": "Document Verification",
      "acceptance_criteria": "Design complies with local codes and project specs",
      "frequency": "Once per project",
      "records": "",
      "control_forms": "",
      "qa_reference": "Electrical Drawings, PEC/NFPA Standards",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 130,
      "row": 185,
      "category": "ELECTRICAL SYSTEM",
      "trade": "ELECTRICAL WORKS",
      "item_no": "2.",
      "description": "Material Submittal Approval",
      "characteristics": "Cable specs, breaker ratings, fixture types, manufacturer data sheets",
      "procedure": "Certification & Spec Review",
      "acceptance_criteria": "Materials match approved specs and standards",
      "frequency": "Once per material type",
      "records": "Purchase request form",
      "control_forms": "",
      "qa_reference": "Submittals, Manufacturer Certifications",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 131,
      "row": 186,
      "category": "ELECTRICAL SYSTEM",
      "trade": "ELECTRICAL WORKS",
      "item_no": "3.",
      "description": "Cable Tray Installation",
      "characteristics": "Tray type, support spacing, alignment, bonding, load rating",
      "procedure": "Visual & Alignment Check",
      "acceptance_criteria": "Trays securely mounted; aligned; bonded; supports per spec",
      "frequency": "Per tray section",
      "records": "Electrical works checklist form",
      "control_forms": "FM\u2010OPN\u201002\u201029",
      "qa_reference": "Cable Tray Layout, NEC/NEMA Standards",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 132,
      "row": 187,
      "category": "ELECTRICAL SYSTEM",
      "trade": "ELECTRICAL WORKS",
      "item_no": "4.",
      "description": "Cable Routing & Conduit Works",
      "characteristics": "Cable type, insulation, support spacing, bend radius, labeling",
      "procedure": "Visual & Continuity Test",
      "acceptance_criteria": "Proper routing; no damage; labeled correctly",
      "frequency": "Per circuit or zone",
      "records": "Electrical works checklist form",
      "control_forms": "FM\u2010OPN\u201002\u201029",
      "qa_reference": "Wiring Diagram, Method Statement",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 133,
      "row": 188,
      "category": "ELECTRICAL SYSTEM",
      "trade": "ELECTRICAL WORKS",
      "item_no": "5.",
      "description": "Panel Board Installation",
      "characteristics": "Mounting, breaker configuration, labeling, accessibility",
      "procedure": "Visual & Functional Check",
      "acceptance_criteria": "Secure installation; operational breakers; clear labeling",
      "frequency": "Per panel",
      "records": "Electrical works checklist form",
      "control_forms": "FM\u2010OPN\u201002\u201029",
      "qa_reference": "Panel Schedule, Manufacturer Instructions",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 134,
      "row": 189,
      "category": "ELECTRICAL SYSTEM",
      "trade": "ELECTRICAL WORKS",
      "item_no": "6.",
      "description": "Grounding System Installation",
      "characteristics": "Rod depth, conductor size, connection integrity",
      "procedure": "Resistance Test",
      "acceptance_criteria": "Ground resistance within limits (e.g., <5 ohms)",
      "frequency": "Per grounding point",
      "records": "Electrical works checklist form",
      "control_forms": "FM\u2010OPN\u201002\u201029",
      "qa_reference": "Grounding Plan, Test Procedure",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 135,
      "row": 190,
      "category": "ELECTRICAL SYSTEM",
      "trade": "ELECTRICAL WORKS",
      "item_no": "7.",
      "description": "Lighting & Power Outlet Installation",
      "characteristics": "Fixture alignment, switch height, socket polarity",
      "procedure": "Visual & Polarity Test",
      "acceptance_criteria": "Devices correctly wired and functional",
      "frequency": "Per fixture/device",
      "records": "Electrical works checklist form",
      "control_forms": "FM\u2010OPN\u201002\u201029",
      "qa_reference": "Fixture Spec, Electrical Layout",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 136,
      "row": 191,
      "category": "ELECTRICAL SYSTEM",
      "trade": "ELECTRICAL WORKS",
      "item_no": "8.",
      "description": "Emergency System Setup",
      "characteristics": "Battery backup, emergency lights, exit signs",
      "procedure": "Functional Test",
      "acceptance_criteria": "Emergency systems operational during power failure",
      "frequency": "Per emergency zone/system",
      "records": "Electrical works checklist form",
      "control_forms": "FM\u2010OPN\u201002\u201029",
      "qa_reference": "Emergency Layout, Fire Code",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 137,
      "row": 192,
      "category": "ELECTRICAL SYSTEM",
      "trade": "ELECTRICAL WORKS",
      "item_no": "9.",
      "description": "Labeling",
      "characteristics": "Label format, location (both ends), legibility, durability",
      "procedure": "Visual & Document Review",
      "acceptance_criteria": "Labels match drawings; heat/smudge resistant; standardized format",
      "frequency": "Per cable/ Tray run, per panel board, per breaker",
      "records": "Electrical works checklist form",
      "control_forms": "FM\u2010OPN\u201002\u201029",
      "qa_reference": "Labeling Plan, As-built Drawings",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 138,
      "row": 193,
      "category": "ELECTRICAL SYSTEM",
      "trade": "ELECTRICAL WORKS",
      "item_no": "10.",
      "description": "Insulation Resistance Testing",
      "characteristics": "Resistance between conductors and ground",
      "procedure": "Megger Test",
      "acceptance_criteria": "Meets code (e.g., >1 M\u03a9 for 500V test)",
      "frequency": "Per circuit",
      "records": "Electrical works checklist form",
      "control_forms": "FM\u2010OPN\u201002\u201029",
      "qa_reference": "Test Report, PEC/NFPA Guidelines",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 139,
      "row": 194,
      "category": "ELECTRICAL SYSTEM",
      "trade": "ELECTRICAL WORKS",
      "item_no": "11.",
      "description": "Functional Testing of Circuits",
      "characteristics": "Circuit continuity, breaker tripping, voltage levels",
      "procedure": "Load & Operation Test",
      "acceptance_criteria": "All circuits operational; breakers trip correctly",
      "frequency": "Per circuit/system",
      "records": "Electrical works checklist form",
      "control_forms": "FM\u2010OPN\u201002\u201029",
      "qa_reference": "Commissioning Checklist",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 140,
      "row": 195,
      "category": "ELECTRICAL SYSTEM",
      "trade": "ELECTRICAL WORKS",
      "item_no": "12.",
      "description": "System Integration (BMS, FDAS, etc.)",
      "characteristics": "Signal transmission, device response, alarm activation",
      "procedure": "End-to-End Test",
      "acceptance_criteria": "Integrated systems respond correctly and log events",
      "frequency": "Once per integrated system",
      "records": "Electrical works checklist form",
      "control_forms": "FM\u2010OPN\u201002\u201029",
      "qa_reference": "Integration Plan, NFPA/IEC Standards",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    },
    {
      "id": 141,
      "row": 196,
      "category": "ELECTRICAL SYSTEM",
      "trade": "ELECTRICAL WORKS",
      "item_no": "13.",
      "description": "Final Inspection & Handover",
      "characteristics": "As-built drawings, test certificates, user manuals",
      "procedure": "Visual & Document Review",
      "acceptance_criteria": "All documentation complete; systems approved by authority",
      "frequency": "Once per project",
      "records": "Commisioning report",
      "control_forms": "",
      "qa_reference": "As-built Drawings, Handover Checklist",
      "subcon": "X",
      "gencon": "S",
      "consultant": "S"
    }
  ]
};
